import archived from "./archived.json" with { type: "json" };
import pinned from "./pinned.json" with { type: "json" };
import community from "./11ty-community.json" with { type: "json" };
import emeritus from "./11ty-emeritus.json" with { type: "json" };
import starters from "./11ty-starters.json" with { type: "json" };

/**
 * Starter projects and templates.
 *
 * Mostly imported from 11ty/docs, which is the canonical list — its `demo`
 * field is the deployed site, and entries it marks `excludedFromLeaderboards`
 * are honoured rather than second-guessed. `EXTRA_STARTERS` is for anything
 * spotted in the community list that upstream does not carry.
 *
 * The union also filters the community category: a starter that appears in both
 * lists belongs here, and deleting it from the generated community file would
 * only last until the next import. Excluding it at this level keeps that file
 * exactly as upstream sends it.
 */
const EXTRA_STARTERS = [
	"https://11skeleton.vercel.app/",
	"https://eleventy-test-bed-dollplayer2501.netlify.app/",
	"https://eleventy-step.netlify.app/",
];
const STARTERS = [...new Set([...starters.urls, ...EXTRA_STARTERS])];

/**
 * Sites that used to be built with Eleventy or Build Awesome.
 *
 * `config/11ty-emeritus.json` holds the bulk of them, recovered from the
 * community repo's git history. `EXTRA_EMERITUS` is the place to add one by
 * hand — a site you know has moved on but whose page says nothing either way,
 * so the generator rule cannot see it.
 *
 * Nothing needs adding here for the ordinary case: a site measured as a
 * different generator is moved automatically at report time. This is only for
 * what measurement cannot detect.
 *
 * Like STARTERS, the union also filters the community category, so a URL listed
 * here leaves Built Awesome rather than appearing in both.
 *
 * Normalized form: https, trailing slash on a bare origin, none on a path.
 */
const EXTRA_EMERITUS = ["https://annotator.incubator.apache.org/"];

/**
 * Community sites added by hand.
 *
 * `config/11ty-community.json` is generated by scripts/import-11ty-community.mjs
 * and rewritten whole on every import, so a URL added there lasts until the next
 * run. This is where one goes to stay — for sites that belong on the list but
 * are not on it upstream, or were dropped from it and should not have been.
 *
 * Anything here almost certainly wants pinning too: the category moves a site
 * out when its page reports a generator other than Eleventy, and a site being
 * re-added by hand is usually one that reports something unusual. See
 * `pinned` below.
 */
const EXTRA_COMMUNITY = [
	"https://cassettenest.com/",
	"https://open-wc.org/",
	"https://www.ryzokuken.dev/",
];
const EMERITUS = [...new Set([...emeritus.urls, ...EXTRA_EMERITUS])];

/**
 * The list of sites to measure.
 *
 * Add or remove entries here — everything else (results, history, the static
 * site) keys off of the `url`, so renaming a site keeps its history but
 * changing a URL starts a fresh history for that URL.
 */
/**
 * Sites taken out of circulation.
 *
 * Archiving is the middle option. Deleting a URL loses its measurements and
 * leaves an orphaned history behind; leaving it in place keeps a dead site in
 * the rankings and keeps sending traffic to it. An archived site keeps its
 * record, stops being measured, and appears only as plain text — no row, no
 * link, no page.
 *
 * Applies across every category at once, so a URL listed in two of them does
 * not need archiving twice.
 */
const ARCHIVED = archived.urls;

/**
 * Sites held where this config puts them.
 *
 * Categories normally reclassify themselves: `requireGenerator` moves a site out
 * of Built Awesome when its page reports something else, and `rejectGenerator`
 * moves it back out of Emeritus when it reports Eleventy again. That is right
 * almost always, and it re-applies on every build — so a category change made by
 * hand does not survive the next report unless the detection agrees with it.
 *
 * This is the exception list for when detection is reading the page correctly
 * and still getting the answer wrong: a stale generator tag left in a template,
 * a proxy or platform stamping its own, a site built with one thing and
 * reporting another. A URL here keeps whatever categories it is listed in.
 *
 * Not a way to disagree with a correct detection. A site that really has moved
 * to Astro belongs in Emeritus, and pinning it there would make this list a
 * quiet second source of truth about what built the web.
 */
const PINNED = pinned.urls;

export default {
	// Read by lib/config.js, which marks the matching sites as it flattens the
	// groups — one place rather than a filter on each category's list.
	archived: ARCHIVED,

	// Exempt from the generator rules, same mechanism. A site entry can also
	// carry `pinGroup: true` directly, for the hand-written categories; this list
	// is for the ones whose entries come from a generated file.
	pinned: PINNED,

	// Lighthouse runs per URL per measurement. The median run is kept.
	// 3 is a decent tradeoff between noise and wall-clock time.
	runs: 3,

	// Whether to keep Lighthouse's loading filmstrip: "filmstrip" or "none",
	// overridable per category and per site.
	//
	// These files are committed, since measure and publish are separate
	// workflows on separate checkouts and the repository is the only channel
	// between them. A deduplicated strip measured 19–84 KB per site, so at this
	// corpus size expect roughly 75 MB in the tree, rewritten weekly as sites
	// are re-measured. Set a category to "none" to keep it out.
	screenshots: "filmstrip",

	// "mobile" (throttled, Moto G Power emulation) or "desktop"
	formFactor: "mobile",

	// Skip a URL if it was already measured within this many hours.
	// Set to 0 to always re-measure.
	freshnessHours: 24 * 7,

	// How many sites a single `speedlify measure` will do before stopping.
	// Measurement is a rolling process: each run spends this budget on whichever
	// sites are most out of date, so you size this to the time you're willing to
	// give one invocation, not to the length of the site list.
	//
	// With ~2,300 sites this must not be null — an unbounded run would try the
	// whole list and take about eleven hours. At 40, a run is roughly 12 minutes,
	// and four shards every two hours cover every site in a bit over a day.
	batchSize: 40,

	// Data older than this is shown as stale in the report and in `speedlify list`.
	staleAfterHours: 24 * 7 * 2,

	// How many recent points the report charts. Since the build reads the compact
	// series.json rather than the raw records, this is a readability choice
	// rather than a performance guard — set it to null to chart everything.
	historyLimit: 120,

	// How long a site whose last attempt errored waits before being tried again.
	// An error is not data, so a failure never earns the site a freshness window
	// — this is the only thing holding it back. 0 means the very next run.
	//
	// Overridable per category, same as freshnessHours: a handful of framework
	// home pages can retry immediately while thousands of personal sites wait.
	retryErrorsAfterHours: 6,

	// Escalate that wait exponentially with each consecutive failure — 1h, 2, 4,
	// 8, 16, capped at 24 — so a URL that has been dead for a week stops
	// consuming a slot in every batch. The two compose: the wait is whichever of
	// the curve and retryErrorsAfterHours is longer.
	failureBackoff: true,

	// A redirect must lead to the same destination on this many consecutive
	// successful measurements before it is treated as a real site move. Guards
	// against A/B tests, geo splits and maintenance pages, which all look like
	// redirects for a run or two.
	redirectConfirmations: 3,

	// Any category can be switched off with `enabled: false`. It stops being
	// measured and stops appearing on the site, but nothing is deleted — its
	// stored history stays put and comes straight back when it is re-enabled.
	//
	// A site listed in a disabled category and nowhere else drops out of the
	// corpus entirely, so its history will read as orphaned meanwhile.
	groups: {
		ssg: {
			name: "Site Generators",
			enabled: true,
			description: "Home pages for popular site generators and frameworks.",
			freshnessHours: 24,
  		staleAfterHours: 48,
			// The list from https://www.speedlify.dev/ssg/, in its order.
			sites: [
				{ name: "Eleventy", url: "https://www.11ty.dev/" },
				{ name: "Astro", url: "https://astro.build/" },
				{ name: "Svelte", url: "https://svelte.dev/" },
				{ name: "Hugo", url: "https://gohugo.io/" },
				{ name: "Jekyll", url: "https://jekyllrb.com/" },
				{ name: "VuePress", url: "https://vuepress.vuejs.org/" },
				{ name: "VitePress", url: "https://vitepress.dev/" },
				{ name: "Docusaurus", url: "https://docusaurus.io/" },
				{ name: "Gridsome", url: "https://gridsome.org/" },
				{ name: "Next.js", url: "https://nextjs.org/" },
				{ name: "Gatsby", url: "https://www.gatsbyjs.com/" },
				{ name: "React Router", url: "https://reactrouter.com/" },
				{ name: "Lume", url: "https://lume.land/" },
				{ name: "Hexo", url: "https://hexo.io/" },
				{ name: "Remix", url: "https://remix.run/" },
				{ name: "SolidJS", url: "https://www.solidjs.com/" },
				{ name: "Qwik", url: "https://qwik.dev/" },
				{ name: "TanStack", url: "https://tanstack.com/" },
				{ name: "Nuxt", url: "https://nuxt.com/" },

				// Added here rather than in the imported order above: the upstream
				// list predates it.
				{ name: "Zola", url: "https://www.getzola.org/" },
			],
		},

		"test-runners": {
			name: "Test Runners",
			enabled: true,
			description: "Home pages for JavaScript test runners and linters.",
			freshnessHours: 24,
  		staleAfterHours: 48,
			// The list from https://www.speedlify.dev/test-runners/, in its order.
			sites: [
				{ name: "QUnit", url: "https://qunitjs.com/" },
				{ name: "webhint", url: "https://webhint.io/" },
				{ name: "Mocha", url: "https://mochajs.org/" },
				{ name: "ESLint", url: "https://eslint.org/" },
				{ name: "Istanbul", url: "https://istanbul.js.org/" },
				{ name: "gulp", url: "https://gulpjs.com/" },
				{ name: "Grunt", url: "https://gruntjs.com/" },
				{ name: "WebdriverIO", url: "https://webdriver.io/" },
				{ name: "Intern", url: "https://theintern.io/" },
			],
		},

		hosts: {
			name: "Web Hosts",
			enabled: true,
			description:
				"Home pages of the hosting and deploy platforms this project detects in the Host column.",

			// A curated handful of company sites, so the same cadence as the other
			// hand-maintained categories rather than the address book's weekly pace.
			freshnessHours: 24,
			staleAfterHours: 48,

			sites: [
				{ name: "Netlify", url: "https://www.netlify.com/" },
				{ name: "Vercel", url: "https://vercel.com/" },
				{ name: "Cloudflare", url: "https://www.cloudflare.com/" },
				{ name: "Cloudflare Pages", url: "https://pages.cloudflare.com/" },
				{ name: "GitHub Pages", url: "https://pages.github.com/" },
				{ name: "GitLab Pages", url: "https://docs.gitlab.com/user/project/pages/" },
				{ name: "Fly.io", url: "https://fly.io/" },
				{ name: "Render", url: "https://render.com/" },
				{ name: "Railway", url: "https://railway.com/" },
				{ name: "Deno Deploy", url: "https://deno.com/deploy" },
				{ name: "Fastly", url: "https://www.fastly.com/" },
				{ name: "Bunny", url: "https://bunny.net/" },
				{ name: "DigitalOcean", url: "https://www.digitalocean.com/" },
				{ name: "Heroku", url: "https://www.heroku.com/" },
				{ name: "Surge", url: "https://surge.sh/" },
				{ name: "Neocities", url: "https://neocities.org/" },
				{ name: "Codeberg Pages", url: "https://codeberg.page/" },

				// Product pages rather than roots: these three are hosting products
				// inside far larger sites, and the company's front door would be
				// measuring something else entirely.
				{ name: "Firebase Hosting", url: "https://firebase.google.com/products/hosting" },
				{ name: "AWS Amplify", url: "https://aws.amazon.com/amplify/" },
				{ name: "Azure Static Web Apps", url: "https://azure.microsoft.com/en-us/products/app-service/static" },
			],
		},

		zachleat: {
			name: "zachleat.com",
			enabled: true,
			description: "Pages from zachleat.com.",

			// A handful of pages on one site, so the curated cadence — and one
			// origin serving all of them, so the same politeness the other
			// many-pages-per-host categories get.
			freshnessHours: 24,
			staleAfterHours: 48,
			rateLimit: {
				delayMs: 3000,
				hostCooldownMs: 60000,
			},

			sites: [
				{ url: "https://www.zachleat.com/" },
				{ url: "https://www.zachleat.com/about/" },
				{ url: "https://www.zachleat.com/resume/" },
				{ url: "https://www.zachleat.com/twitter/" },
				{ url: "https://www.zachleat.com/web/" },
				{ url: "https://www.zachleat.com/web/eleventy/" },
				{ url: "https://www.zachleat.com/web/fonts/" },
				{ url: "https://www.zachleat.com/web/speedlify/" },
				{ url: "https://www.zachleat.com/web/lighthouse-in-footer/" },
				{ url: "https://www.zachleat.com/web/comprehensive-webfonts/" },
				{ url: "https://www.zachleat.com/web/google-fonts-display/" },
			],
		},

		"11ty-community": {
			name: "Built Awesome",
			enabled: true,
			description:
				'Community-submitted sites from the <a href="https://github.com/11ty/11ty-community">11ty/11ty-community</a> repository.',

			// Same reasoning as Personal Websites: other people's sites, most on
			// modest hosting, measured at a deliberate pace.
			rateLimit: {
				delayMs: 3000,
				hostCooldownMs: 60000,
			},

			freshnessHours: 24 * 7,
			staleAfterHours: 24 * 7 * 2,

			// for storage reasons
			screenshots: "none",

			// The list is a record of what was submitted, not of what is true now.
			// A site measured as something other than Eleventy has moved on, so it
			// moves to the category below rather than inflating this one.
			//
			// Matched on the detected generator's id, and only when there is one:
			// no generator tag is the normal case for a static site and proves
			// nothing either way, so those stay put. Both names for the same
			// project qualify — "Build Awesome" is Eleventy's newer branding and
			// reports under its own id, so it has to be listed explicitly.
			requireGenerator: ["eleventy", "build-awesome"],
			emeritusGroup: "11ty-emeritus",

			// Most static sites emit no generator tag at all, so a blank is the
			// common case here rather than a suspicious one. Being on this list is
			// itself a claim about what built the site — shown faded, because it is
			// what someone submitted rather than what we measured.
			presumedGenerator: "build-awesome",

			// Generated by scripts/import-11ty-community.mjs — re-run it to refresh.
			//
			// Two lists are filtered out rather than deleted from the generated
			// file, which a re-import would only undo: starters, and anything
			// hand-listed as emeritus. Adding a URL to config/11ty-emeritus.json is
			// therefore the whole of moving it — it appears there and leaves here.
			//
			// The automatic path still works alongside this: a site measured as a
			// different generator is moved by requireGenerator below, no editing
			// needed. This is for the cases measurement cannot see.
			sites: [...new Set([...community.urls, ...EXTRA_COMMUNITY])]
				.filter((url) => !STARTERS.includes(url) && !EMERITUS.includes(url))
				.map((url) => ({ url })),
		},

		"11ty-starters": {
			name: "Build Awesome Starters",
			description:
				"Starter projects and templates built with Eleventy. Measured apart from the community list because a starter is a demonstration of a stack rather than a site someone runs.",

			freshnessHours: 24 * 7,
			staleAfterHours: 24 * 7 * 2,
			rateLimit: {
				delayMs: 3000,
				hostCooldownMs: 60000,
			},

			// for storage reasons
			screenshots: "none",

			// The ones that came from the community list were filtered out of it,
			// not missing from it. Without this they would be flagged "unlisted"
			// — told to submit something that is already submitted.
			listedIn: "11ty-community",

			// Kept out of the home page's Perfect Scores board. A starter is a
			// near-empty demonstration page, so a perfect score there is the
			// expected result rather than an achievement, and enough of them would
			// crowd out the real sites the board exists to show. They still rank
			// normally on their own category page and in the global leaderboard.
			excludeFromPerfectScores: true,

			// Same reasoning as the community list above: a starter emits no
			// generator tag any more often than a finished site does, and being on
			// this list is itself a claim about what built it. Shown faded, because
			// it is what the docs say rather than what we measured.
			//
			// No requireGenerator to go with it, unlike the community list. A
			// starter that stops being Eleventy stops being an Eleventy starter and
			// gets removed upstream; there is no "used to be a starter" category for
			// it to age into.
			presumedGenerator: "build-awesome",

			// Generated by scripts/import-11ty-starters.mjs — re-run it to refresh.

			sites: STARTERS.map((url) => ({ url })),
		},

		"11ty-emeritus": {
			name: "11ty Emeritus",

			// Not a competition. These sites left, and ranking what they scored on
			// the way out invites a reading nobody intended — that the list is a
			// wall of shame, or that the site at the top is the best of a bad lot.
			// The page still measures them; it just does not place them.
			ranked: false,

			enabled: true,
			description:
				"Sites that were previously built with Eleventy or Build Awesome but have moved away (since April 2018).",

			// Same deliberate pace as the community list it came from.
			rateLimit: {
				delayMs: 3000,
				hostCooldownMs: 60000,
			},

			freshnessHours: 24 * 7,
			staleAfterHours: 24 * 7 * 2,

			// for storage reasons
			screenshots: "none",

			// Two ways in. Sites listed here were deleted from the community repo
			// upstream — recovered from its git history, since a deletion removes
			// the URL entirely and the generator rule never gets to see it.
			//
			// The rest arrive at report time: anything still on the community list
			// that measures as a different generator is moved here automatically.
			// The category is defined by what a site *used* to be built with, so one
			// measuring as Eleventy again does not belong here — it has come back,
			// and saying otherwise would state the opposite of the truth. The
			// mirror image of requireGenerator above.
			//
			// As there, an undetected generator decides nothing: most static sites
			// emit no tag, and absence is not evidence of a return.
			rejectGenerator: ["eleventy", "build-awesome"],
			rejectGroup: "11ty-community",

			sites: EMERITUS.map((url) => ({ url })),
		},
	},
};
